spring:
  profiles:
    active: dev,local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #springboot 1.5.10版本上传文件配置方式
  http:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 6MB
#      location: uploaded/image/










